### ISSUE TITLE
Arguments not being passed to `grid_card`

### ISSUE THREAD

**Issue by MikeJohnPage** [rstudio/gridlayout#13]
The `grid_card_text()` function does not appear to be passing on arguments to `grid_card()` using the ellipsis. For example setting `has_border = FALSE` in `grid_card_text()` does not remove the border from the card. Reprex below:

```r
library(shiny)
library(gridlayout)

ui <- grid_page(
  layout = c(
    "    1fr   ",
    "1fr header"
  ),
  grid_card_text("header", "Test header", has_border = FALSE)
)

server <- function(input, output) {
}

shinyApp(ui, server)
```
I'm not sure if this is my user error or an error with the function. Any help would be appreciated.

**Comment by nstrayer** [comment]
So sorry this issue completely slipped by me. I'll check on this today. It's probable I forgot to pass through arguments for `grid_card_text()`.

**Comment by nstrayer** [comment]
My intuition was correct. I just neglected to send the dot args anywhere. This is fixed in #14 and will be merged when it passes checks.

**Comment by nstrayer** [comment]
Thanks so much for submitting the issue! I apologize again for the slow response.

**Comment by MikeJohnPage** [comment]
No need to apologise! Thanks for taking a look at this. If I checkout your pull request #14 locally and rerun my reprex from above, a border still appears:

<img width="1231" alt="gridlayout" src="https://user-images.githubusercontent.com/38110953/194506173-d6e62b89-290a-434f-9726-2d56c8ffe731.png">

I presume setting `has_border = FALSE` should be removing the border that can be seen above, and not something else?

**Comment by nstrayer** [comment]
Interesting. Are you sure you restarted the R Session etc? Here's what I get with the PR:
```r
library(shiny)
library(gridlayout)

ui <- grid_page(
  layout = c(
    "A",
    "B"
  ),
  grid_card_text("A", "Default (with border)"),
  grid_card_text("B", "has_border = FALSE", has_border = FALSE)
)

server <- function(input, output) {
}

shinyApp(ui, server)
```
![image](https://user-images.githubusercontent.com/6764693/194649724-e6568032-850f-4077-ad8a-c30ef9948a73.png)

**Comment by MikeJohnPage** [comment]
Oops... I was loading the old version of gridlayout still on the library search path. All working now. Thanks again for your work on the package!
